# All comments below were generated by ChatGPT.
# It even knew from context that the input file should contain integers.

# Open the file "01_input.txt" in read mode and create a file object
with open("01_input.txt") as file:
    # Read all lines of the file into a list
    input_list = file.readlines()

# Initialize an empty list to store the numbers from the file
elves = []

# Iterate over each line in the input list
for line in input_list:
    try:
        # Try to append the integer representation of the line to the last element of the elves list
        elves[-1] += int(line)
    except:
        # If the line is empty or cannot be converted to an integer, append a new element with a value of 0 to the elves list
        elves.append(0)

# Sort the elves list in descending order
elves.sort(reverse=True)

# Print the sum of the first three elements of the elves list
# (which will be the sum of the three largest numbers in the list)
print(sum(elves[:3]))
